//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupLuxParibahanWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int reservationNO { get; set; }
        public string UTKNo { get; set; }
        public string userEmail { get; set; }
        public string coachNo { get; set; }
        public string bookedSeat { get; set; }
        public string reservationDate { get; set; }
        public string dateOfJourney { get; set; }
        public string paymentMethod { get; set; }
        public int duePayment { get; set; }
    
        public virtual tripData tripData { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
